### ISSUE TITLE
Add Relationships without "include"

### ISSUE THREAD

**Issue by Estigy** [nilportugues/symfony-jsonapi#10]
Hi, Nil.

Is there a way to add Relationships without adding the whole Entity to the "include" block?

And is there a way to do some kind of dynamic mapping, meaning that in one case I want to output a User entity with all its Comments, and in another case I don't want to include the Comments.

Thanks! Estigy.

**Comment by nilportugues** [comment]
> And is there a way to do some kind of dynamic mapping, meaning that in one case I want to output a User entity with all its Comments, and in another case I don't want to include the Comments.
> For the alternate Comments section it is easy, you'll need to create another class. 

Lets say, you have the `Posts` model. I'm assuming you've got relations set up to a `Comments` model. 

If you want one without the Comments, all you need to do is: 

```php
<?php 

class PostsWithoutComments extends Posts
{
}
```
And then: 
 - Create a new mapping for the `PostsWithoutComments` model. 
 - Use the `PostsWithoutComments` as you would use `Posts`.

Why this should work: 
- Eloquent creates relationships based on class name. Because you of this, unless you map back Comments to `PostWithoutComments`, comments won' t be fetched.
