### ISSUE TITLE
Unserialization to symfony entity

### ISSUE THREAD

**Issue by franbenz** [nilportugues/symfony-jsonapi#19]
Is there a way to get an entity from a json received via POST request using json api? Maybe this needs to use the mappings needed for serialization in a reverse way.

**Comment by nilportugues** [comment]
@franbenz Short answer, no.

Why? JSONAPI does not cover transforming to a certain object type in a programming language. This library follows the spec at jsonapi.org. 

While what you ask if possible to be implemented and can be done, this can be build because of the nature of JSONAPI and it's predictable data-structure, but doesn't come in bundled with this package.
